//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lakandula.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class enrollmentEntities : DbContext
    {
        public enrollmentEntities()
            : base("name=enrollmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<batch> batches { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<employeestatu> employeestatus { get; set; }
        public virtual DbSet<enrolledsubject> enrolledsubjects { get; set; }
        public virtual DbSet<faculty> faculties { get; set; }
        public virtual DbSet<gender> genders { get; set; }
        public virtual DbSet<gradestatu> gradestatus { get; set; }
        public virtual DbSet<opensubject> opensubjects { get; set; }
        public virtual DbSet<room> rooms { get; set; }
        public virtual DbSet<section> sections { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<studentstatu> studentstatus { get; set; }
        public virtual DbSet<subject> subjects { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<usertype> usertypes { get; set; }
        public virtual DbSet<yearlevel> yearlevels { get; set; }
    }
}
