//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lakandula.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class enrolledsubject
    {
        public int id { get; set; }
        public int studentid { get; set; }
        public int opensubjectid { get; set; }
        public string firstgradinggrade { get; set; }
        public string secondgradinggrade { get; set; }
        public string thirdgradinggrade { get; set; }
        public string fourthgradinggrade { get; set; }
        public string finalgrade { get; set; }
        public int gradestatusid { get; set; }
    
        public virtual gradestatu gradestatu { get; set; }
        public virtual opensubject opensubject { get; set; }
        public virtual student student { get; set; }
    }
}
