//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lakandula.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class faculty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public faculty()
        {
            this.opensubjects = new HashSet<opensubject>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int genderid { get; set; }
        public System.DateTime birthdate { get; set; }
        public string address { get; set; }
        public string contact { get; set; }
        public string empno { get; set; }
        public int empstatusid { get; set; }
        public int departmentId { get; set; }
        public string email { get; set; }
        public byte[] profilepic { get; set; }
    
        public virtual department department { get; set; }
        public virtual employeestatu employeestatu { get; set; }
        public virtual gender gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<opensubject> opensubjects { get; set; }
    }
}
