//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lakandula.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class opensubject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public opensubject()
        {
            this.enrolledsubjects = new HashSet<enrolledsubject>();
        }
    
        public int id { get; set; }
        public int batchid { get; set; }
        public int facultyid { get; set; }
        public int roomid { get; set; }
        public int sectionid { get; set; }
        public int subjectid { get; set; }
        public System.TimeSpan starttime { get; set; }
        public System.TimeSpan endtime { get; set; }
    
        public virtual batch batch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enrolledsubject> enrolledsubjects { get; set; }
        public virtual faculty faculty { get; set; }
        public virtual room room { get; set; }
        public virtual section section { get; set; }
        public virtual subject subject { get; set; }
    }
}
