//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lakandula.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public student()
        {
            this.enrolledsubjects = new HashSet<enrolledsubject>();
        }
    
        public int id { get; set; }
        public string lrn { get; set; }
        public string name { get; set; }
        public int genderid { get; set; }
        public System.DateTime birthday { get; set; }
        public string birthplace { get; set; }
        public string address { get; set; }
        public string citizenship { get; set; }
        public string contact { get; set; }
        public string email { get; set; }
        public string fathername { get; set; }
        public string fatheroccupation { get; set; }
        public string mothername { get; set; }
        public string motheroccupation { get; set; }
        public string guardian { get; set; }
        public string guardiancontact { get; set; }
        public byte[] profilepic { get; set; }
        public int status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enrolledsubject> enrolledsubjects { get; set; }
        public virtual gender gender { get; set; }
        public virtual studentstatu studentstatu { get; set; }
    }
}
